CREATE TABLE IF NOT EXISTS `cases` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `caseNumber` VARCHAR(50) NOT NULL UNIQUE,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT,
  `status` ENUM('draft', 'open', 'investigating', 'evidence_gathering', 'dispute_filed', 'awaiting_response', 'under_review', 'escalated', 'resolved_won', 'resolved_lost', 'closed') DEFAULT 'draft' NOT NULL,
  `priority` ENUM('low', 'medium', 'high', 'urgent') DEFAULT 'medium' NOT NULL,
  `caseType` VARCHAR(100) NOT NULL,
  `carrier` VARCHAR(100),
  `trackingNumber` VARCHAR(100),
  `claimAmount` DECIMAL(10, 2),
  `recoveredAmount` DECIMAL(10, 2),
  `customerName` VARCHAR(255),
  `customerEmail` VARCHAR(320),
  `customerPhone` VARCHAR(50),
  `shippingAddress1` VARCHAR(255),
  `shippingAddress2` VARCHAR(255),
  `shippingCity` VARCHAR(100),
  `shippingState` VARCHAR(50),
  `shippingZip` VARCHAR(20),
  `shippingCountry` VARCHAR(100),
  `billingAddress1` VARCHAR(255),
  `billingAddress2` VARCHAR(255),
  `billingCity` VARCHAR(100),
  `billingState` VARCHAR(50),
  `billingZip` VARCHAR(20),
  `billingCountry` VARCHAR(100),
  `orderNumber` VARCHAR(100),
  `orderDate` TIMESTAMP NULL,
  `orderTotal` DECIMAL(10, 2),
  `productSku` VARCHAR(100),
  `productName` VARCHAR(500),
  `productQuantity` INT,
  `productPrice` DECIMAL(10, 2),
  `serviceType` VARCHAR(100),
  `actualDimensions` VARCHAR(100),
  `carrierStatedDimensions` VARCHAR(100),
  `dimensionsMismatch` BOOLEAN DEFAULT FALSE,
  `closestTubeSize` VARCHAR(50),
  `dimensionDifference` DECIMAL(10, 2),
  `assignedTo` INT,
  `templateId` INT,
  `aiSuccessProbability` INT,
  `aiRecommendation` TEXT,
  `dueDate` TIMESTAMP NULL,
  `resolvedAt` TIMESTAMP NULL,
  `isFlagged` INT DEFAULT 0 NOT NULL,
  `flagReason` TEXT,
  `flaggedAt` TIMESTAMP NULL,
  `createdBy` INT NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX `case_number_idx` (`caseNumber`),
  INDEX `status_idx` (`status`),
  INDEX `carrier_idx` (`carrier`),
  INDEX `tracking_idx` (`trackingNumber`),
  INDEX `created_by_idx` (`createdBy`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
