CREATE TABLE IF NOT EXISTS calendar_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  calendar_connection_id INT NOT NULL,
  external_event_id VARCHAR(255) NOT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT,
  location VARCHAR(500),
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  all_day BOOLEAN DEFAULT FALSE,
  attendees JSON COMMENT 'Array of attendee emails',
  organizer_email VARCHAR(320),
  status VARCHAR(50) DEFAULT 'confirmed' COMMENT 'confirmed, tentative, cancelled',
  entity_type VARCHAR(50) COMMENT 'customer, vendor, lead, contact',
  entity_id INT,
  created_in_crm BOOLEAN DEFAULT FALSE,
  synced_to_external BOOLEAN DEFAULT FALSE,
  last_synced_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (calendar_connection_id) REFERENCES calendar_connections(id) ON DELETE CASCADE,
  UNIQUE KEY unique_external_event (calendar_connection_id, external_event_id),
  INDEX idx_start_time (start_time),
  INDEX idx_entity (entity_type, entity_id),
  INDEX idx_status (status)
);
