INSERT INTO products (
  sku, name, description, category, weight, dimensions, cost, price, margin, 
  supplier, leadTimeDays, isActive, lifecycleState, intelligenceMetadata, 
  variantSummary, lastIntelligenceUpdate, createdAt, updatedAt
) VALUES 
(
  'FISH-LINE-PRO-20LB',
  'ProCast Fishing Line - 20lb Test',
  'Premium monofilament fishing line with enhanced abrasion resistance. Perfect for freshwater and light saltwater fishing.',
  'Fishing Line',
  0.5,
  '4x4x1',
  8.50,
  24.99,
  16.49,
  'Fishing Gear Wholesale Inc',
  14,
  true,
  'development',
  '{"assets":[{"type":"product_images","status":"in_progress"},{"type":"packaging_design","status":"completed"},{"type":"marketing_copy","status":"completed"}],"requirements":[{"name":"Product Photography","completed":false},{"name":"Packaging Design","completed":true},{"name":"Marketing Copy","completed":true},{"name":"Inventory Stocked","completed":false}],"readinessScore":65,"blockers":["Awaiting product photography","Initial inventory order pending"]}',
  '{"total":3,"ready":1,"blocked":2,"avgReadiness":55}',
  NOW(),
  NOW(),
  NOW()
),
(
  'TACKLE-BOX-ELITE',
  'Elite Tackle Storage System',
  'Professional-grade tackle box with 8 compartments, waterproof seals, and rust-resistant latches. Holds up to 200 pieces of tackle.',
  'Tackle Storage',
  3.2,
  '14x9x8',
  22.00,
  59.99,
  37.99,
  'Outdoor Gear Direct',
  21,
  true,
  'pre_launch',
  '{"assets":[{"type":"product_images","status":"completed"},{"type":"packaging_design","status":"completed"},{"type":"marketing_copy","status":"completed"},{"type":"instruction_manual","status":"completed"}],"requirements":[{"name":"Product Photography","completed":true},{"name":"Packaging Design","completed":true},{"name":"Marketing Copy","completed":true},{"name":"Inventory Stocked","completed":true},{"name":"Listing Created","completed":false}],"readinessScore":88,"blockers":["Awaiting final listing approval"]}',
  '{"total":2,"ready":2,"blocked":0,"avgReadiness":92}',
  NOW(),
  NOW(),
  NOW()
),
(
  'LURE-COMBO-BASS',
  'Bass Master Lure Collection',
  'Complete bass fishing lure set with 12 proven patterns. Includes crankbaits, spinnerbaits, and soft plastics in a premium storage case.',
  'Fishing Lures',
  1.8,
  '10x7x3',
  15.50,
  44.99,
  29.49,
  'Lure Manufacturers Ltd',
  28,
  true,
  'concept',
  '{"assets":[{"type":"product_images","status":"not_started"},{"type":"packaging_design","status":"in_progress"},{"type":"marketing_copy","status":"not_started"}],"requirements":[{"name":"Product Photography","completed":false},{"name":"Packaging Design","completed":false},{"name":"Marketing Copy","completed":false},{"name":"Inventory Stocked","completed":false},{"name":"Supplier Contract","completed":true}],"readinessScore":22,"blockers":["Awaiting prototype samples","Packaging design not started","No marketing materials"]}',
  '{"total":1,"ready":0,"blocked":1,"avgReadiness":20}',
  NOW(),
  NOW(),
  NOW()
);
