CREATE TABLE `emailAccounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountName` varchar(255) NOT NULL,
	`emailAddress` varchar(320) NOT NULL,
	`provider` enum('SMTP','GMAIL_API','ZOHO') NOT NULL,
	`smtpHost` varchar(255),
	`smtpPort` int,
	`smtpUsername` varchar(255),
	`smtpPassword` text,
	`smtpSecure` int NOT NULL DEFAULT 1,
	`apiCredentials` text,
	`isDefault` int NOT NULL DEFAULT 0,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `emailAccounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `emailCommunications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int,
	`emailAccountId` int NOT NULL,
	`direction` enum('SENT','RECEIVED') NOT NULL,
	`fromAddress` varchar(320) NOT NULL,
	`toAddresses` text NOT NULL,
	`ccAddresses` text,
	`bccAddresses` text,
	`subject` text NOT NULL,
	`bodyHtml` text,
	`bodyText` text,
	`attachments` text,
	`status` enum('DRAFT','SENDING','SENT','DELIVERED','FAILED','BOUNCED') NOT NULL DEFAULT 'DRAFT',
	`errorMessage` text,
	`messageId` varchar(255),
	`inReplyTo` varchar(255),
	`threadId` varchar(255),
	`sentAt` timestamp,
	`deliveredAt` timestamp,
	`openedAt` timestamp,
	`repliedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `emailCommunications_id` PRIMARY KEY(`id`)
);
