CREATE TABLE `emailTemplateSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`companyName` varchar(255) DEFAULT 'Catch The Fever',
	`logoUrl` varchar(500),
	`primaryColor` varchar(7) DEFAULT '#2c5f2d',
	`secondaryColor` varchar(7) DEFAULT '#10b981',
	`headerText` varchar(255) DEFAULT 'New Draft Case Created',
	`headerIcon` varchar(10) DEFAULT '🚨',
	`footerText` text,
	`footerLinks` text,
	`introText` text,
	`ctaButtonText` varchar(100) DEFAULT 'Review Case',
	`ctaButtonColor` varchar(7) DEFAULT '#2c5f2d',
	`fromName` varchar(255),
	`fromEmail` varchar(255),
	`replyToEmail` varchar(255),
	`enableNewCaseNotifications` int NOT NULL DEFAULT 1,
	`enableBulkNotifications` int NOT NULL DEFAULT 1,
	`enableStatusChangeNotifications` int NOT NULL DEFAULT 0,
	`isDefault` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `emailTemplateSettings_id` PRIMARY KEY(`id`)
);
