CREATE TABLE `caseTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`category` varchar(100),
	`tags` text,
	`carrier` enum('FEDEX','UPS','USPS','DHL','OTHER'),
	`caseType` enum('DAMAGE','ADJUSTMENT','SLA'),
	`priority` enum('LOW','MEDIUM','HIGH','URGENT'),
	`serviceType` varchar(100),
	`damageType` enum('TUBE','ROD','TIP','BENT_EYE','STRUCTURAL','PACKAGING','OTHER'),
	`damageSeverity` enum('MINOR','MODERATE','SEVERE','TOTAL_LOSS'),
	`templateNotes` text,
	`disputeReasonTemplate` text,
	`insuranceProvider` varchar(255),
	`carrierGuarantee` boolean DEFAULT false,
	`usageCount` int NOT NULL DEFAULT 0,
	`lastUsedAt` timestamp,
	`isPublic` boolean NOT NULL DEFAULT false,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `caseTemplates_id` PRIMARY KEY(`id`)
);
