CREATE TABLE `notificationPreferences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`position` enum('TOP_LEFT','TOP_RIGHT','TOP_CENTER','BOTTOM_LEFT','BOTTOM_RIGHT','BOTTOM_CENTER') NOT NULL DEFAULT 'TOP_RIGHT',
	`size` enum('COMPACT','NORMAL','LARGE') NOT NULL DEFAULT 'NORMAL',
	`colors` text,
	`borderRadius` int NOT NULL DEFAULT 8,
	`shadowIntensity` int NOT NULL DEFAULT 3,
	`opacity` int NOT NULL DEFAULT 100,
	`fontSize` int NOT NULL DEFAULT 14,
	`animationType` enum('SLIDE','FADE','BOUNCE','SCALE','FLIP','NONE') NOT NULL DEFAULT 'SLIDE',
	`animationDuration` int NOT NULL DEFAULT 300,
	`animationEasing` varchar(50) NOT NULL DEFAULT 'ease-in-out',
	`soundEnabled` boolean NOT NULL DEFAULT true,
	`soundType` varchar(50) NOT NULL DEFAULT 'default',
	`soundVolume` int NOT NULL DEFAULT 50,
	`vibrationEnabled` boolean NOT NULL DEFAULT true,
	`vibrationPattern` varchar(100) NOT NULL DEFAULT 'short',
	`showIcons` boolean NOT NULL DEFAULT true,
	`showTimestamps` boolean NOT NULL DEFAULT true,
	`showActionButtons` boolean NOT NULL DEFAULT true,
	`showCloseButton` boolean NOT NULL DEFAULT true,
	`timestampFormat` varchar(50) NOT NULL DEFAULT 'relative',
	`iconStyle` varchar(50) NOT NULL DEFAULT 'filled',
	`autoDismiss` boolean NOT NULL DEFAULT true,
	`autoDismissDuration` int NOT NULL DEFAULT 5000,
	`maxNotifications` int NOT NULL DEFAULT 5,
	`stackBehavior` enum('STACK','REPLACE','QUEUE') NOT NULL DEFAULT 'STACK',
	`enableInfo` boolean NOT NULL DEFAULT true,
	`enableSuccess` boolean NOT NULL DEFAULT true,
	`enableWarning` boolean NOT NULL DEFAULT true,
	`enableError` boolean NOT NULL DEFAULT true,
	`quietHoursEnabled` boolean NOT NULL DEFAULT false,
	`quietHoursStart` varchar(5),
	`quietHoursEnd` varchar(5),
	`doNotDisturb` boolean NOT NULL DEFAULT false,
	`groupSimilar` boolean NOT NULL DEFAULT true,
	`groupingWindow` int NOT NULL DEFAULT 60000,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notificationPreferences_id` PRIMARY KEY(`id`),
	CONSTRAINT `notificationPreferences_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('INFO','SUCCESS','WARNING','ERROR') NOT NULL,
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`link` varchar(500),
	`linkText` varchar(100),
	`icon` varchar(50),
	`relatedCaseId` int,
	`relatedType` varchar(50),
	`relatedId` int,
	`isRead` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`priority` enum('LOW','NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL',
	`deliveryMethod` varchar(100) NOT NULL DEFAULT 'IN_APP',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
