CREATE TABLE `carrierPortalConfigs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`carrier` enum('FEDEX','UPS','USPS','DHL') NOT NULL,
	`loginUrl` text NOT NULL,
	`claimsUrl` text,
	`trackingUrl` text,
	`loginSelectors` text,
	`claimFormSelectors` text,
	`maxConcurrentSessions` int NOT NULL DEFAULT 1,
	`sessionTimeout` int NOT NULL DEFAULT 1800,
	`retryDelay` int NOT NULL DEFAULT 300,
	`hasCaptcha` boolean NOT NULL DEFAULT false,
	`captchaType` enum('NONE','RECAPTCHA_V2','RECAPTCHA_V3','HCAPTCHA','IMAGE'),
	`captchaSelector` text,
	`maxFileSize` int NOT NULL DEFAULT 10485760,
	`allowedFileTypes` text,
	`maxFilesPerClaim` int NOT NULL DEFAULT 10,
	`claimFilingDeadline` int NOT NULL DEFAULT 60,
	`minClaimAmount` int NOT NULL DEFAULT 0,
	`maxClaimAmount` int,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`lastTested` timestamp,
	`testStatus` enum('PASSED','FAILED','NOT_TESTED') DEFAULT 'NOT_TESTED',
	`notes` text,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `carrierPortalConfigs_id` PRIMARY KEY(`id`),
	CONSTRAINT `carrierPortalConfigs_carrier_unique` UNIQUE(`carrier`)
);
--> statement-breakpoint
CREATE TABLE `carrierPortalCredentials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`carrier` enum('FEDEX','UPS','USPS','DHL') NOT NULL,
	`accountName` varchar(255) NOT NULL,
	`username` text NOT NULL,
	`password` text NOT NULL,
	`accountNumber` text,
	`securityQuestions` text,
	`twoFactorMethod` enum('NONE','SMS','EMAIL','AUTHENTICATOR') DEFAULT 'NONE',
	`twoFactorPhone` text,
	`twoFactorEmail` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`isShared` boolean NOT NULL DEFAULT false,
	`lastUsed` timestamp,
	`lastValidated` timestamp,
	`validationStatus` enum('VALID','INVALID','NEEDS_VERIFICATION','EXPIRED') DEFAULT 'NEEDS_VERIFICATION',
	`notes` text,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `carrierPortalCredentials_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portalSessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(100) NOT NULL,
	`carrier` enum('FEDEX','UPS','USPS','DHL') NOT NULL,
	`credentialId` int NOT NULL,
	`status` enum('ACTIVE','IDLE','EXPIRED','CLOSED') NOT NULL DEFAULT 'ACTIVE',
	`cookies` text,
	`localStorage` text,
	`sessionStorage` text,
	`lastActivity` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp NOT NULL,
	`keepAlive` boolean NOT NULL DEFAULT false,
	`submissionsCount` int NOT NULL DEFAULT 0,
	`lastSubmissionAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `portalSessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `portalSessions_sessionId_unique` UNIQUE(`sessionId`)
);
--> statement-breakpoint
CREATE TABLE `portalSubmissionHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int NOT NULL,
	`caseId` int NOT NULL,
	`carrier` enum('FEDEX','UPS','USPS','DHL') NOT NULL,
	`action` varchar(100) NOT NULL,
	`status` enum('SUCCESS','FAILED','WARNING') NOT NULL,
	`message` text,
	`screenshotUrl` text,
	`pageUrl` text,
	`elementSelector` text,
	`errorStack` text,
	`duration` int,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `portalSubmissionHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portalSubmissionQueue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`carrier` enum('FEDEX','UPS','USPS','DHL') NOT NULL,
	`credentialId` int NOT NULL,
	`status` enum('QUEUED','IN_PROGRESS','COMPLETED','FAILED','CANCELLED','NEEDS_CAPTCHA','NEEDS_2FA') NOT NULL DEFAULT 'QUEUED',
	`priority` enum('LOW','MEDIUM','HIGH','URGENT') NOT NULL DEFAULT 'MEDIUM',
	`submissionType` enum('NEW_CLAIM','APPEAL','FOLLOW_UP','DOCUMENT_UPLOAD') NOT NULL DEFAULT 'NEW_CLAIM',
	`formData` text,
	`attachments` text,
	`attemptCount` int NOT NULL DEFAULT 0,
	`maxAttempts` int NOT NULL DEFAULT 3,
	`lastAttemptAt` timestamp,
	`nextAttemptAt` timestamp,
	`confirmationNumber` varchar(100),
	`claimNumber` varchar(100),
	`screenshotUrl` text,
	`errorMessage` text,
	`errorDetails` text,
	`browserSessionId` varchar(100),
	`executionDuration` int,
	`captchaSolved` boolean DEFAULT false,
	`twoFactorCompleted` boolean DEFAULT false,
	`scheduledFor` timestamp,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `portalSubmissionQueue_id` PRIMARY KEY(`id`)
);
