CREATE TABLE `workflowExecutionSteps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`executionId` int NOT NULL,
	`nodeId` varchar(100) NOT NULL,
	`nodeType` varchar(100) NOT NULL,
	`nodeName` varchar(255),
	`status` enum('PENDING','RUNNING','COMPLETED','FAILED','SKIPPED') NOT NULL DEFAULT 'PENDING',
	`input` text,
	`output` text,
	`errorMessage` text,
	`errorStack` text,
	`retryCount` int NOT NULL DEFAULT 0,
	`maxRetries` int NOT NULL DEFAULT 3,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`duration` int,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `workflowExecutionSteps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workflowExecutions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workflowId` int NOT NULL,
	`caseId` int,
	`status` enum('PENDING','RUNNING','PAUSED','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
	`currentNodeId` varchar(100),
	`completedNodes` text,
	`failedNodes` text,
	`context` text,
	`output` text,
	`errorMessage` text,
	`errorDetails` text,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`pausedAt` timestamp,
	`resumedAt` timestamp,
	`triggerSource` varchar(100),
	`triggerData` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workflowExecutions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workflowNodeTypes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` varchar(100) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`category` enum('ACTION','CONDITION','TRIGGER','INTEGRATION','UTILITY') NOT NULL,
	`configSchema` text,
	`icon` varchar(100),
	`color` varchar(50),
	`isAsync` boolean NOT NULL DEFAULT false,
	`requiresHumanInput` boolean NOT NULL DEFAULT false,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workflowNodeTypes_id` PRIMARY KEY(`id`),
	CONSTRAINT `workflowNodeTypes_type_unique` UNIQUE(`type`)
);
--> statement-breakpoint
CREATE TABLE `workflowTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` enum('CASE_LIFECYCLE','APPEAL_PROCESS','ESCALATION','CUSTOM') NOT NULL,
	`nodes` text NOT NULL,
	`edges` text NOT NULL,
	`category` varchar(100),
	`tags` text,
	`usageCount` int NOT NULL DEFAULT 0,
	`isPublic` boolean NOT NULL DEFAULT false,
	`isOfficial` boolean NOT NULL DEFAULT false,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workflowTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workflows` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` enum('CASE_LIFECYCLE','APPEAL_PROCESS','ESCALATION','CUSTOM') NOT NULL DEFAULT 'CUSTOM',
	`nodes` text NOT NULL,
	`edges` text NOT NULL,
	`triggerType` enum('MANUAL','CASE_CREATED','STATUS_CHANGE','TIME_BASED','WEBHOOK') NOT NULL DEFAULT 'MANUAL',
	`triggerConditions` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`isTemplate` boolean NOT NULL DEFAULT false,
	`executionCount` int NOT NULL DEFAULT 0,
	`successCount` int NOT NULL DEFAULT 0,
	`failureCount` int NOT NULL DEFAULT 0,
	`tags` text,
	`category` varchar(100),
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workflows_id` PRIMARY KEY(`id`)
);
