CREATE TABLE `bankTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionDate` timestamp NOT NULL,
	`amount` int NOT NULL,
	`description` text,
	`transactionType` varchar(50),
	`bankAccountId` varchar(100),
	`bankTransactionId` varchar(255),
	`checkNumber` varchar(100),
	`category` varchar(100),
	`isCarrierPayment` boolean DEFAULT false,
	`detectedCarrier` enum('FEDEX','UPS','USPS','DHL','OTHER'),
	`paymentRecordId` int,
	`isReconciled` boolean DEFAULT false,
	`importBatchId` varchar(100),
	`importedAt` timestamp DEFAULT (now()),
	`rawData` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bankTransactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `bankTransactions_bankTransactionId_unique` UNIQUE(`bankTransactionId`)
);
--> statement-breakpoint
CREATE TABLE `paymentMatchingSuggestions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`paymentRecordId` int NOT NULL,
	`caseId` int NOT NULL,
	`confidence` int NOT NULL,
	`matchScore` int NOT NULL,
	`amountMatch` int,
	`dateMatch` int,
	`carrierMatch` int,
	`referenceMatch` int,
	`matchReason` text,
	`matchDetails` text,
	`status` enum('PENDING','ACCEPTED','REJECTED','EXPIRED') NOT NULL DEFAULT 'PENDING',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `paymentMatchingSuggestions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paymentRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int,
	`paymentAmount` int NOT NULL,
	`paymentMethod` enum('CHECK','ACH','CREDIT','WIRE','OTHER') NOT NULL,
	`paymentDate` timestamp NOT NULL,
	`checkNumber` varchar(100),
	`checkImageUrl` text,
	`bankTransactionId` varchar(255),
	`bankDescription` text,
	`carrier` enum('FEDEX','UPS','USPS','DHL','OTHER'),
	`carrierReference` varchar(255),
	`reconciliationStatus` enum('UNMATCHED','MATCHED','DISPUTED','VERIFIED') NOT NULL DEFAULT 'UNMATCHED',
	`matchConfidence` int DEFAULT 0,
	`matchedAt` timestamp,
	`matchedBy` int,
	`matchMethod` enum('AUTO','MANUAL','AI_SUGGESTED'),
	`expectedAmount` int,
	`discrepancyAmount` int,
	`discrepancyReason` text,
	`notes` text,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paymentRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reconciliationRules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`carrier` enum('FEDEX','UPS','USPS','DHL','ALL') NOT NULL,
	`matchCriteria` text NOT NULL,
	`amountTolerancePercent` int DEFAULT 5,
	`dateToleranceDays` int DEFAULT 30,
	`minimumConfidence` int DEFAULT 70,
	`autoMatch` boolean DEFAULT false,
	`requiresApproval` boolean DEFAULT true,
	`isActive` boolean DEFAULT true,
	`priority` int DEFAULT 0,
	`matchCount` int DEFAULT 0,
	`successRate` int DEFAULT 0,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reconciliationRules_id` PRIMARY KEY(`id`)
);
