CREATE TABLE `companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`website` varchar(500),
	`industry` varchar(100),
	`accountType` enum('prospect','customer','partner','competitor') NOT NULL DEFAULT 'prospect',
	`tier` enum('enterprise','mid-market','smb'),
	`annualRevenue` int,
	`lifetimeValue` int DEFAULT 0,
	`parentCompanyId` int,
	`address` varchar(500),
	`city` varchar(100),
	`state` varchar(50),
	`zipCode` varchar(20),
	`country` varchar(100) DEFAULT 'USA',
	`tags` text,
	`customFields` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	CONSTRAINT `companies_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320),
	`phone` varchar(50),
	`jobTitle` varchar(255),
	`contactType` enum('direct_owned','marketplace','b2b_distributor','b2b_wholesale','vendor','raw_data') NOT NULL,
	`lifecycleStage` enum('lead','mql','sql','opportunity','customer','advocate','churned') NOT NULL DEFAULT 'lead',
	`companyId` int,
	`ownerId` int,
	`leadScore` int DEFAULT 0,
	`healthScore` int DEFAULT 100,
	`lifetimeValue` int DEFAULT 0,
	`churnProbability` int DEFAULT 0,
	`nextPurchaseDate` timestamp,
	`address` varchar(500),
	`city` varchar(100),
	`state` varchar(50),
	`zipCode` varchar(20),
	`country` varchar(100) DEFAULT 'USA',
	`lastActivityAt` timestamp,
	`lastContactedAt` timestamp,
	`emailOptIn` int NOT NULL DEFAULT 1,
	`smsOptIn` int NOT NULL DEFAULT 0,
	`tags` text,
	`customFields` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`companyId` int,
	`contactId` int,
	`ownerId` int NOT NULL,
	`stage` enum('prospecting','qualification','proposal','negotiation','closed_won','closed_lost') NOT NULL DEFAULT 'prospecting',
	`amount` int,
	`probability` int DEFAULT 10,
	`expectedCloseDate` timestamp,
	`actualCloseDate` timestamp,
	`lossReason` varchar(255),
	`competitorName` varchar(255),
	`tags` text,
	`customFields` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	CONSTRAINT `deals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `distributors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`contactName` varchar(255),
	`email` varchar(320),
	`phone` varchar(50),
	`tier` enum('platinum','gold','silver','bronze') NOT NULL DEFAULT 'silver',
	`status` enum('active','inactive','pending','suspended') NOT NULL DEFAULT 'active',
	`territoryRegion` varchar(100),
	`territoryStates` text,
	`territoryZipCodes` text,
	`commissionRate` int,
	`minimumOrder` int,
	`paymentTerms` varchar(100),
	`totalRevenue` int DEFAULT 0,
	`totalOrders` int DEFAULT 0,
	`averageOrderValue` int DEFAULT 0,
	`address` varchar(500),
	`city` varchar(100),
	`state` varchar(50),
	`zipCode` varchar(20),
	`country` varchar(100) DEFAULT 'USA',
	`contractStartDate` timestamp,
	`contractEndDate` timestamp,
	`contractUrl` varchar(500),
	`tags` text,
	`customFields` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	CONSTRAINT `distributors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vendors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`contactName` varchar(255),
	`email` varchar(320),
	`phone` varchar(50),
	`website` varchar(500),
	`vendorType` enum('manufacturer','supplier','service','logistics','technology') NOT NULL,
	`status` enum('active','inactive','pending','suspended') NOT NULL DEFAULT 'active',
	`qualityRating` int DEFAULT 0,
	`deliveryRating` int DEFAULT 0,
	`priceRating` int DEFAULT 0,
	`overallRating` int DEFAULT 0,
	`totalSpend` int DEFAULT 0,
	`totalOrders` int DEFAULT 0,
	`averageLeadTime` int,
	`paymentTerms` varchar(100),
	`address` varchar(500),
	`city` varchar(100),
	`state` varchar(50),
	`zipCode` varchar(20),
	`country` varchar(100) DEFAULT 'USA',
	`contractStartDate` timestamp,
	`contractEndDate` timestamp,
	`contractUrl` varchar(500),
	`certifications` text,
	`insuranceExpiry` timestamp,
	`tags` text,
	`customFields` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	CONSTRAINT `vendors_id` PRIMARY KEY(`id`)
);
